print("    _______    ")
print("   /       \   ")
print("  /   \ /   \  ")
print(" /   *   *   \ ")
print(" \ \   ^   / / ")
print("  \ \_____/ /  ")
print("   \_______/   ")

print(" _")
print("|_|")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("|||")
print("\ /")
print(" .")

print("____                  ____                  ____")
print("\_  \___             /    \             ___/  _/")
print(" \____  \___________| *  * |___________/  ____/ ")
print("  \_  \____________ |  \/  | ____________/  _/  ")
print("   \___             |      |             ___/   ")
print("    \_ \___________ |      | ___________/ _/    ")
print("     \______________/\____/\______________/     ")
print("                      /  \                      ")
print("                     /|\/|\                     ")

input()
